
server:
  port: 8080

spring:
  #配置redis
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 20000
    #配置数据源
  datasource:
    url: jdbc:mysql://hx-htl_ctrip-ctrip_main-master.db.tuniu-sst.org:3306/ctrip_main?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    password: tuniu520
    username: ctrip_main_rw




